### ISSUE TITLE
Release v0.1.0 wheels on PyPI

### ISSUE THREAD

**Issue by jcfr** [ClinicalGraphics/VTKU3DExporter#10]
* [x] Anticipating the publication of the package on PyPI, register a trusted publisher
* [x] Integrate https://github.com/ClinicalGraphics/VTKU3DExporter/pull/9
* [x] Update workflow to publish package using the `pypi` environment registered above
  * https://github.com/ClinicalGraphics/VTKU3DExporter/pull/11
* [x] Document workaround 
  * https://github.com/ClinicalGraphics/VTKU3DExporter/issues/13
  * https://github.com/ClinicalGraphics/VTKU3DExporter/pull/14
* [x] Tag repository to trigger release process

_Copied from https://pypi.org/manage/account/publishing/:_

> Trusted Publisher Management
> 
> OpenID Connect (OIDC) provides a flexible, credential-free mechanism for delegating publishing authority for a PyPI package to a trusted third party service, like GitHub Actions.
> 
> PyPI users and projects can use trusted publishers to automate their release processes, without needing to use API tokens or passwords.
> 
> You can read more about trusted publishers and how to use them [here](https://docs.pypi.org/trusted-publishers/).

**Comment by jcfr** [comment]
> Anticipating the publication of the package on PyPI, register a trusted publisher

![image](https://github.com/ClinicalGraphics/VTKU3DExporter/assets/219043/8de0cf29-0db8-44a4-9268-97ad12c9eabc)

**Comment by Korijn** [comment]
@jcfr did we get our publisher status?

**Comment by jcfr** [comment]
> did we get our publisher status?

All required infrastructure changes to allow upload of the packages have been implemented.

After reviewing https://github.com/ClinicalGraphics/VTKU3DExporter/pull/14, we will release `v0.1.0`.
