### ISSUE TITLE
Improve integration of IFXOSLoader.cpp to remove need for workaround

### ISSUE THREAD

**Issue by jcfr** [ClinicalGraphics/VTKU3DExporter#13]
To workaround current limitation of `IFXOSLoader.cpp`, it is required to set the `U3D_LIBDIR` env. variable to the path where the IFXCore library is located.

```python
# ...

# Workaround current limitation of IFXOSLoader.cpp. This is required
# to ensure the IFXCore library can be loaded.
os.environ["U3D_LIBDIR"] = os.path.dirname(vtkU3DExporter.__file__)
    
# Define the output file name, which will have the ".u3d" extension appended automatically
filePath = "cube"

# Export to U3D
u3dExporter = vtkU3DExporter.vtkU3DExporter()
u3dExporter.SetFileName(filePath)
u3dExporter.SetInput(renderWindow)
u3dExporter.Write()
```

## Next steps

The `u3d` project could be simplified by removing the abstraction requiring to call `IFXCOMInitialize()` which in turn instantiate the `IFXCoreLib` itself calling `IFXLoadCoreLibrary()`, which then  calls `IFXLoadLibrary` to load `libIFXCore` expected to be in the `U3D_LIBDIR` directory.

Before doing so, also need to assess how the plugins `libIFXExporting`, `libIFXImporting`, `libIFXScheduling` and `libIFXRendering` are loaded through `CIFXComponentManager::CreateComponent`.

**Comment by jcfr** [comment]
After reviewing the possible way of addressing this, it turns out a simpler approach will be to get the path of the compiled vtk-u3dexporter module directly from C++.

This could be doing something like this:

```
// Get the path for the library
  std::string libPath = vtkResourceFileLocator::GetLibraryPathForSymbolWin32("vtkU3DExporter");
  std::string u3dLibDir = vtksys::SystemTools::GetFilenamePath(libPath);
```

Notes: 
- set the env. variable if not already set.

- Will have to confirm GetLibraryPathForSymbolWin32 can be used to get path of current module

**Comment by Korijn** [comment]
Is this only a requirement for Win32?
